"use client";
import { CmsText } from "@/components/cms-context";

import Image from "@/components/cms-image";
import { ArrowDown, ArrowUpRight, ChevronDown, Heart, KeyRound, Mail, MapPin, Phone, Trees, Users } from "lucide-react";
import { Navigation } from "@/components/navigation";
import { Ratings, Stars } from "@/components/ratings";
import { Houses } from "@/components/houses";
import { Gallery } from "@/components/gallery";
import { Booking, LocationMap, ReviewsWidget } from "@/components/embeds";
import { useSite } from "@/components/cms-context";
import { Brand, Foliage } from "@/components/brand";
import { ContactLinks } from "@/components/contact-links";
import { Company, ExtraServices, Spa, WhyTangerine } from "@/components/holiday-sections";

export default function Landing() {
  const {site, reviewExcerpts, rules} = useSite();
  return <div id="top"><Navigation/><main id="main">
    <section className="hero" aria-labelledby="hero-heading">
      <Image src="/images/hero.jpg" alt="Дома «Танжерин» и зелёный сад с местом для отдыха" fill priority sizes="100vw" className="hero-photo"/>
      <div className="hero-shade"/>
      <Foliage className="hero-leaves" variant="palm" eager/>
      <Foliage className="hero-citrus" variant="leaves" eager/>
      <div className="container hero-inner">
        <div className="hero-eyebrow"><span className="little-sun">✳</span> <CmsText id="landing.001" fallback="ГОСТЕВЫЕ ДОМА В КОСТРОМЕ" /></div>
        <h1 id="hero-heading"><CmsText id="landing.002" fallback="ТАНЖЕРИН" /><span><CmsText id="landing.003" fallback="Место, где Вы дома" /></span></h1>
        <p><CmsText id="landing.004" fallback="Три самостоятельных дома для семей," />{" "}<br className="desktop-break"/> <CmsText id="landing.005" fallback="друзей и больших компаний." /><br/> <CmsText id="landing.006" fallback="Своя кухня, веранда и мангальная зона —" />{" "}<br className="desktop-break"/> <CmsText id="landing.007" fallback="а до центра Костромы около 3 км." /></p>
        <div className="hero-actions"><a className="button button-yellow" href="#booking"><CmsText id="landing.008" fallback="Проверить стоимость и забронировать" /><ArrowUpRight size={19}/></a><a className="hero-secondary" href="#houses"><CmsText id="landing.009" fallback="Посмотреть дома" /><ArrowUpRight size={18}/></a></div>
        <div className="hero-capacity"><span><Users size={23}/><span><strong><CmsText id="landing.010" fallback="До 10 гостей" /></strong><small><CmsText id="landing.011" fallback="в одном доме" /></small></span></span><span><HouseIcon/><span><strong><CmsText id="landing.012" fallback="До 25 гостей" /></strong><small><CmsText id="landing.013" fallback="рядом" /></small></span></span></div>
        <div className="hero-bottom"><span><MapPin size={17}/> <CmsText id="landing.014" fallback="Кострома · 3 км до центра" /></span><a href="#about" aria-label="Узнать о Танжерине"><ArrowDown size={20}/></a><span><CmsText id="landing.015" fallback="Кухня · веранда · парковка" /></span></div>
      </div>
    </section>
    <section className="trust-section botanical-section" aria-label="Рейтинги гостей"><Foliage className="trust-leaves"/><Foliage className="trust-fruit" fruit/><div className="container"><div className="trust-message"><Heart size={23} strokeWidth={1.2}/><h2><CmsText id="landing.016" fallback="Оценки наших гостей" /></h2><p><CmsText id="landing.017" fallback="Яндекс Карты, 2ГИС и Google Maps" /></p></div><div className="trust-strip"><Ratings compact/></div><a className="trust-more text-link" href="#reviews"><CmsText id="landing.018" fallback="Читать отзывы гостей" /><ArrowUpRight size={16}/></a></div></section>
    <section className="section container about" id="about">
      <div><div className="eyebrow"><CmsText id="landing.019" fallback="О ТАНЖЕРИНЕ" /></div><h2><CmsText id="landing.020" fallback="Дома в Костроме" /><br/><span className="muted"><CmsText id="landing.021" fallback="с кухней и верандой" /></span></h2></div>
      <div className="about-copy"><p><CmsText id="landing.022" fallback="В «Танжерине» вы снимаете целый дом с отдельными спальнями, кухней и верандой. Можно готовить самим, припарковать машину на территории и приехать с детьми." /></p><p><CmsText id="landing.023" fallback="Мы находимся в районе Черноречья, рядом с Волгой, примерно в 3 км от центра Костромы. Принимаем гостей с 2018 года." /></p><div className="about-facts"><span><KeyRound/><strong>3</strong><small><CmsText id="landing.024" fallback="дома для гостей" /></small></span><span><MapPin/><strong><CmsText id="landing.025" fallback="3 км" /></strong><small><CmsText id="landing.026" fallback="до центра Костромы" /></small></span><span><Trees/><strong><CmsText id="landing.027" fallback="Свой сад" /></strong><small><CmsText id="landing.028" fallback="на территории" /></small></span></div></div>
    </section>
    <section className="houses-section section botanical-section" id="houses"><Foliage className="houses-leaves" variant="palm"/><Foliage className="houses-lemons" variant="lemons"/><div className="container">
      <div className="section-heading houses-heading"><div><div className="eyebrow"><CmsText id="landing.029" fallback="ДОМА И РАЗМЕЩЕНИЕ" /></div><h2><CmsText id="landing.030" fallback="Выберите дом по числу гостей" /></h2></div><p><CmsText id="landing.031" fallback="От 67 до 100 м², от двух до четырёх спален." />{" "}<br className="desktop-break"/> <CmsText id="landing.032" fallback="Посмотрите фотографии и сравните удобства." /></p></div>
      <Houses/>
    </div></section>
    <Company/>
    <WhyTangerine/>
    <Spa/>
    <ExtraServices/>
    <section className="atmosphere" aria-labelledby="atmosphere-title"><div className="atmosphere-picture"><Image src="/images/veranda.jpg" alt="Веранда таунхауса для отдыха с близкими" fill sizes="100vw"/></div><div className="atmosphere-copy"><Foliage className="atmosphere-leaves"/><div className="eyebrow"><CmsText id="landing.033" fallback="ВЕРАНДА И ТЕРРИТОРИЯ" /></div><h2 id="atmosphere-title"><CmsText id="landing.034" fallback="Веранда и мангал" /><br/><span><CmsText id="landing.035" fallback="у каждого дома" /></span></h2><p><CmsText id="landing.036" fallback="У каждого дома — своя крытая веранда со столом и мангальная зона. Можно поужинать на улице, не выезжая с территории." /></p><a className="text-link light-link" href="#booking"><CmsText id="landing.037" fallback="Выбрать даты поездки" /><ArrowUpRight size={19}/></a></div></section>
    <section className="section container" id="gallery"><div className="section-heading"><div><div className="eyebrow"><CmsText id="landing.038" fallback="ФОТОГРАФИИ" /></div><h2><CmsText id="landing.039" fallback="Дома, комнаты и территория" /></h2></div><span className="gallery-caption"><CmsText id="landing.040" fallback="Настоящие фотографии наших домов и территории" /><ArrowDown size={17}/></span></div><Gallery/></section>
    <section className="reviews-section section botanical-section" id="reviews"><Foliage className="reviews-leaves"/><div className="container"><div className="section-heading"><div><div className="eyebrow"><CmsText id="landing.041" fallback="ОТЗЫВЫ ГОСТЕЙ" /></div><h2><CmsText id="landing.042" fallback="Что пишут о проживании" /></h2></div><a className="text-link" href={site.yandex} target="_blank" rel="noreferrer"><CmsText id="landing.043" fallback="206 отзывов на Яндекс Картах" /><ArrowUpRight size={18}/></a></div><Ratings/><p className="ratings-date"><CmsText id="landing.044" fallback="Рейтинги проверены" />{" "}{site.checked}<CmsText id="landing.045" fallback=". Актуальные оценки — в карточках площадок." /></p><div className="review-cards">{reviewExcerpts.map(review=><article className="review-card" key={review.name}><div className="review-top"><Stars/><Image src="/images/yandex-logo.jpg" alt="Яндекс Карты" width={40} height={30}/></div><blockquote>«{review.quote}»</blockquote><div className="review-author"><span className="avatar-initials">{review.initials}</span><div><strong>{review.name}</strong><span>{review.date} <CmsText id="landing.046" fallback="· Яндекс Карты" /></span></div></div><a href={site.yandex} target="_blank" rel="noreferrer"><CmsText id="landing.047" fallback="Читать полный отзыв" /><ArrowUpRight size={14}/></a></article>)}</div><ReviewsWidget/></div></section>
    <section className="section container host-section"><div className="host-photo"><Image src="/images/host.jpg" alt="Светлана, хозяйка таунхаусов «Танжерин»" fill sizes="(max-width:760px) 90vw, 380px"/></div><div className="host-copy"><div className="eyebrow"><CmsText id="landing.048" fallback="ВАШ КОНТАКТ ПЕРЕД ПОЕЗДКОЙ" /></div><h2><CmsText id="landing.049" fallback="Будем знакомы." /><br/><CmsText id="landing.050" fallback="Я — Светлана." /></h2><p><CmsText id="landing.051" fallback="Я занимаюсь размещением гостей в «Танжерине». Если не знаете, какой дом выбрать, напишите, сколько вас и когда планируете приехать." /></p><p><CmsText id="landing.052" fallback="Подскажу по спальным местам, проживанию с детьми и питомцами, условиям SPA. Перед приездом объясню, как добраться и заселиться." /></p><a className="text-link" href={site.telegram} target="_blank" rel="noreferrer"><CmsText id="landing.053" fallback="Написать Светлане" /><ArrowUpRight size={18}/></a></div><Heart className="host-heart" size={48} strokeWidth={1}/></section>
    <section className="booking-section section botanical-section" id="booking"><Image className="section-backdrop" src="/images/family-living.jpg" alt="" fill sizes="100vw"/><div className="container"><div className="booking-intro"><div className="eyebrow"><CmsText id="landing.054" fallback="БРОНИРОВАНИЕ" /></div><h2><CmsText id="landing.055" fallback="Проверьте свободные" /><br/><CmsText id="landing.056" fallback="даты и стоимость" /></h2><p><CmsText id="landing.057" fallback="Укажите даты и число гостей. В форме появятся доступные дома и цена проживания. Если нужны два или три дома сразу, напишите Светлане." /></p><Foliage className="booking-fruit" fruit/></div><Booking/></div></section>
    <section className="section container rules-section" id="rules"><div><div className="eyebrow"><CmsText id="landing.058" fallback="ПЕРЕД ПОЕЗДКОЙ" /></div><h2><CmsText id="landing.059" fallback="Перед бронированием" /></h2><p><CmsText id="landing.060" fallback="Остались вопросы?" /><br/><CmsText id="landing.061" fallback="Позвоните Светлане." /></p><a className="text-link" href={site.phoneHref}>{site.phone} <ArrowUpRight size={18}/></a></div><div className="faq">{rules.map((rule,index)=><details key={rule.title}><summary><span className="faq-number">0{index+1}</span>{rule.title}<ChevronDown size={18}/></summary><p>{rule.text}</p></details>)}</div></section>
    </main><footer className="footer botanical-section"><Image className="section-backdrop" src="/images/hero.jpg" alt="" fill sizes="100vw"/><Foliage className="footer-palm" variant="palm"/><section className="contacts-section" id="contacts"><div className="container contacts-grid"><div className="contact-copy"><div className="eyebrow"><CmsText id="landing.062" fallback="АДРЕС И КОНТАКТЫ" /></div><h2><CmsText id="landing.063" fallback="Как добраться" /><br/><CmsText id="landing.064" fallback="до «Танжерина»" /></h2><p className="contact-address"><MapPin size={21}/>{site.address}</p><p><CmsText id="landing.065" fallback="Тихий район Черноречья, в 3 км от центра города." /><br/><CmsText id="landing.066" fallback="Рядом — берёзовая роща и набережная Волги." /></p><a className="contact-phone" href={site.phoneHref}>{site.phone}</a><span className="contact-person"><CmsText id="landing.067" fallback="Светлана · по вопросам проживания" /></span><a className="contact-email" href={`mailto:${site.email}`}><Mail size={16}/>{site.email}</a><div className="contact-actions"><a className="button button-dark" href={site.phoneHref}><Phone size={17}/> <CmsText id="landing.068" fallback="Позвонить" /></a><ContactLinks labels/></div><details className="directions"><summary><CmsText id="landing.069" fallback="Как подъехать к дому" /><ChevronDown size={16}/></summary><p><CmsText id="landing.070" fallback="Заезд с улицы Северной Правды на дорогу рядом с магазином «Десяточка». Проезжайте школу № 3 и стадион. После футбольной площадки поверните направо, затем двигайтесь прямо мимо детского сада № 35." /></p></details></div><LocationMap/></div></section>
  <div className="container footer-main"><Brand/><nav aria-label="Навигация в подвале"><a href="#houses"><CmsText id="landing.071" fallback="Наши дома" /></a><a href="#reviews"><CmsText id="landing.072" fallback="Отзывы" /></a><a href="#rules"><CmsText id="landing.073" fallback="Правила проживания" /></a><a href="#contacts"><CmsText id="landing.074" fallback="Контакты" /></a></nav><a href="#top" className="back-top"><CmsText id="landing.075" fallback="Наверх" /><ArrowUpRight size={18}/></a></div><div className="container footer-bottom"><span><CmsText id="landing.076" fallback="© 2026 «Танжерин»" /></span><span><CmsText id="landing.077" fallback="Гостевые дома в Костроме" /></span><a href={site.booking} target="_blank" rel="noreferrer"><CmsText id="landing.078" fallback="Условия бронирования" /><ArrowUpRight size={13}/></a></div></footer></div>;
}

function HouseIcon(){return <Trees size={25} strokeWidth={1.5}/>;}

